### PR TITLE
Made Weather App With Current Weather

### PR DESCRIPTION
**Pull request by raazseth**
I made a weather app with current weather fetching from weatherapi by detecting the user's current location (lat and long) and this weather app is made on ReactJS as a frontend library.

Kindly, Please accept this PR!

### CODE REVIEW

**Comment by shivanidotcom** [comment]
Yea sure can you keep the video of it!

**Comment by raazseth** [comment]
Yeah Sure! 

Do I have to upload it somewhere?

**Comment by shivanidotcom** [comment]
Send here

**Comment by raazseth** [comment]
It's just a simple weather web app fetching data from weather API. You can have a look here!

[6c5f5c8d-f7bf-4fbc-97c9-8bd16ab19fe1.webm](https://user-images.githubusercontent.com/37039751/196715532-9f1d5501-689f-4417-a008-5dc28bf3a163.webm)

**Comment by shivanidotcom** [comment]
Ok I'll look into it

**Pull request merged**
